export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const AUTH_USER = "AUTH_USER";
export const AUTH_LOGIN_START = "AUTH_LOGIN_START";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_GET_INFO_FAIL = "AUTH_LOGIN_GET_INFO_FAIL";
export const AUTH_SET_USER_DETAIL = "AUTH_SET_USER_DETAIL";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";
export const AUTH_SET_REDIRECT_PATH = "AUTH_SET_REDIRECT_PATH";

export const AUTH_SET_STOMP_CLIENT = "AUTH_SET_STOMP_CLIENT";
export const AUTH_CLEAR_STOMP_CLIENT = "AUTH_CLEAR_STOMP_CLIENT";

export const MESSAGE_SET_MESSAGE = "MESSAGE_SET_MESSAGE";
export const MESSAGE_CLEAR_MESSAGE = "MESSAGE_CLEAR_MESSAGE";

export const FETCH_PRODUCTS_START = "FETCH_PRODUCTS_START";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";

export const FETCH_ORDERS = {
  start: "FETCH_ORDERS_START",
  success: "FETCH_ORDERS_SUCCESS",
  fail: "FETCH_ORDERS_FAIL",
};

export const ORDER_ADD_TO_CART = "ORDER_ADD_TO_CART";
export const ORDER_DELETE_FROM_CART = "ORDER_DELETE_FROM_CART";
export const ORDER_UPDATE_CART = "ORDER_UPDATE_CART";
export const ORDER_UPDATE_SERVICE_TIME_ADDRESS =
  "ORDER_UPDATE_SERVICE_TIME_ADDRESS";
export const ORDER_SWITCH_TO_PAYMENT = "ORDER_SWITCH_TO_PAYMENT";
export const ORDER_UPDATE_PAYMENT_INFO = "ORDER_UPDATE_PAYMENT_INFO";
export const ORDER_RESET_STATUS = "ORDER_RESET_STATUS";
export const ORDER_SET_BACK_STATUS = "ORDER_SET_BACK_STATUS";
export const ORDER_CLEAR_CART = "ORDER_CLEAR_CART";
export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";

export const registerConstants = {
  REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
  REGISTER_FAILURE: "USERS_REGISTER_FAILURE",
  REGISTER_RESET: "USERS_REGISTER_RESET",
};

export const ORDER_PLACE_ORDER_START = "ORDER_PLACE_ORDER_START";
export const ORDER_PLACE_ORDER_SUCCESS = "ORDER_PLACE_ORDER_SUCCESS";
export const ORDER_PLACE_ORDER_FAIL = "ORDER_PLACE_ORDER_FAIL";

// provider related
export const PROVIDER_FETCH_SERVICES = {
  start: "PROVIDER_FETCH_SERVICES_START",
  success: "PROVIDER_FETCH_SERVICES_SUCCESS",
  fail: "PROVIDER_FETCH_SERVICES_FAIL",
};
export const PROVIDER_DECLINE_REQUEST = "PROVIDER_DECLINE_REQUEST";
export const PROVIDER_UPDATE_SERVICE_STATUS = {
  start: "PROVIDER_UPDATE_SERVICE_STATUS_START",
  success: "PROVIDER_UPDATE_SERVICE_STATUS_SUCCESS",
  fail: "PROVIDER_UPDATE_SERVICE_STATUS_FAIL",
};
export const PROVIDER_ADD_PUSHED_REQUEST = "PROVIDER_ADD_PUSH_REQUEST";
export const PROVIDER_CLEAR_PUSHED_REQUEST = "PROVIDER_CLEAR_PUSH_REQUEST";
