export const sampleProducts = [
  {
    product_id: 5,
    category: "Blowouts",
    name: "Blowout",
    content: "From straight and sleek to beachy waves, achieve your perfect",
    price: 55,
    duration: 55,
  },
  {
    product_id: 6,
    category: "Blowouts",
    name: "Blowout + Braid",
    content: "Playful or polished, try something new with the perfect braid.",
    price: 60,
    duration: 75,
  }, 
  {
    product_id: 9,
    category: "Haircuts",
    name: "Haircut + Blowout",
    content: "Haircuts start with a personalized consultation and end with your favorite blowout.",
    price: 75,
    duration: 100,
  }, 
  {
    product_id: 10,
    category: "Haircuts",
    name: "Short (Men's) Haircut",
    content: "Freshen up your short style with a haircut for lengths above the ear to the chin.",
    price: 75,
    duration: 100,
  },
  {
    product_id: 11,
    category: "Haircuts",
    name: "Kids Haircut",
    content: "Our patient stylists give your youngster a customized haircut they’ll love for age 4 - 12.",
    price: 75,
    duration: 100,
  },
  {
    product_id: 12,
    category: "Makeup",
    name: "Makeup",
    content: "Feel perfectly polishes and put together in no time with our convinent classic manicure.",
    price: 75,
    duration: 100,
  },
  {
    product_id: 14,
    category: "Nails",
    name: "Manicure",
    content: "Feel perfectly polishes and put together in no time with our convinent classic manicure.",
    price: 75,
    duration: 100,
  },
  {
    product_id: 15,
    category: "Nails",
    name: "Pedicure",
    content: "Show your feet some love with a flowless, ultra-gyginenic pedicure from highly experienced nail pros.",
    price: 75,
    duration: 100,
  },
];