export const productList = [
    {
        "productId": 5,
        "category": "Blowouts",
        "productName": "Blowout",
        "productDescription": "From straight and sleek to beachy waves, achieve your perfect hair.",
        "productPrice": 45.0,
        "duration": 55,
        "star": true,
        "imageURL": 'https://i.ibb.co/Y0MHRHR/hairdresser-659139-1920.jpg',
    },
    {
        "productId": 6,
        "category": "Blowouts",
        "productName": "Blowout + Braid",
        "productDescription": "Playful or polished, try something new with the perfect braid.",
        "productPrice": 60.0,
        "duration": 75,
        "star": false,
        "imageURL": 'https://i.ibb.co/Y0MHRHR/hairdresser-659139-1920.jpg',
    },
    {
        "productId": 7,
        "category": "Blowouts",
        "productName": "Special Occation Hair",
        "productDescription": "An elevated service for your most special moments, ideal for red carpet, galas, parties, photoshots and more.",
        "productPrice": 75.0,
        "duration": 100,
        "star": false,
        "imageURL": 'https://i.ibb.co/Y0MHRHR/hairdresser-659139-1920.jpg',
    },
    {
        "productId": 8,
        "category": "Blowouts",
        "productName": "Special Occation updo",
        "productDescription": "An elevated service for your most special moments, ideal for red carpet, galas, parties, photoshots and more.",
        "productPrice": 90.0,
        "duration": 150,
        "star": false,
        "imageURL": 'https://i.ibb.co/Y0MHRHR/hairdresser-659139-1920.jpg',
    },
    {
        "productId": 9,
        "category": "Haircuts",
        "productName": "Haircut + Blowout",
        "productDescription": "Haircuts start with a personalized consultation and end with your favorite blowout.",
        "productPrice": 75.0,
        "duration": 100,
        "star": true,
        "imageURL": 'https://i.ibb.co/Y0MHRHR/hairdresser-659139-1920.jpg',
    },
    {
        "productId": 10,
        "category": "Haircuts",
        "productName": "Short (Men's) Haircut",
        "productDescription": "Freshen up your short style with a haircut for lengths above the ear to the chin.",
        "productPrice": 60.0,
        "duration": 75,
        "star": false,
        "imageURL": 'https://i.ibb.co/Y0MHRHR/hairdresser-659139-1920.jpg',
    },
    {
        "productId": 11,
        "category": "Haircuts",
        "productName": "Kids Haircut",
        "productDescription": "Our patient stylists give your youngster a customized haircut they’ll love for age 4 - 12.",
        "productPrice": 45.0,
        "duration": 60,
        "star": false,
        "imageURL": 'https://i.ibb.co/Y0MHRHR/hairdresser-659139-1920.jpg',
    },
    {
        "productId": 12,
        "category": "Makeup",
        "productName": "Makeup",
        "productDescription": "Feel perfectly polishes and put together in no time with our convinent classic manicure.",
        "productPrice": 45.0,
        "duration": 55,
        "star": true,
        "imageURL": 'https://i.ibb.co/Y0MHRHR/hairdresser-659139-1920.jpg',
    },
    {
        "productId": 13,
        "category": "Makeup",
        "productName": "Special Occasion Makeup",
        "productDescription": "A high touch service for your most special moments, red carpet, galas, parties.",
        "productPrice": 90.0,
        "duration": 150,
        "star": false,
        "imageURL": 'https://i.ibb.co/Y0MHRHR/hairdresser-659139-1920.jpg',
    },
    {
        "productId": 14,
        "category": "Nails",
        "productName": "Manicure",
        "productDescription": "Feel perfectly polishes and put together in no time with our convinent classic manicure.",
        "productPrice": 45.0,
        "duration": 55,
        "star": true,
        "imageURL": 'https://i.ibb.co/Y0MHRHR/hairdresser-659139-1920.jpg',
    },
    {
        "productId": 15,
        "category": "Nails",
        "productName": "Pedicure",
        "productDescription": "Show your feet some love with a flowless, ultra-gyginenic pedicure from highly experienced nail pros.",
        "productPrice": 45.0,
        "duration": 55,
        "star": true,
        "imageURL": 'https://i.ibb.co/Y0MHRHR/hairdresser-659139-1920.jpg',
    },
    {
        "productId": 16,
        "category": "Nails",
        "productName": "Manicure + Pedicure",
        "productDescription": "From straight and sleep to beachy waves, achieve your perfect hair.",
        "productPrice": 90.0,
        "duration": 85,
        "star": false,
        "imageURL": 'https://i.ibb.co/Y0MHRHR/hairdresser-659139-1920.jpg',
    }
];